### ISSUE TITLE
runtime error for demo.jpg -- RuntimeError: Given groups=1, weight of size [256, 512, 3, 3], expected input[1, 3, 46, 32] to have 512 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by ehartz01** [Hzzone/pytorch-openpose#2]
Any idea what's happening?

SED-ML-0148% python demo1.py
Traceback (most recent call last):
  File "demo1.py", line 17, in <module>
    candidate, subset = body_estimation(oriImg)
  File "python/body.py", line 46, in __call__
    Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
  File "/Users/ehartz01/Desktop/SignPhonologizer/nicey/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "python/model.py", line 108, in forward
    out1 = self.model0(x)
  File "/Users/ehartz01/Desktop/SignPhonologizer/nicey/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ehartz01/Desktop/SignPhonologizer/nicey/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/ehartz01/Desktop/SignPhonologizer/nicey/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ehartz01/Desktop/SignPhonologizer/nicey/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 512, 3, 3], expected input[1, 3, 46, 32] to have 512 channels, but got 3 channels instead

**Comment by JiageWang** [comment]
I got the same error. The code uses OrderedDict in the wrong way, you can just turn the parameter from dict to list to remove the bug.
![snipaste_2019-03-04_16-30-09](https://user-images.githubusercontent.com/33656971/53720081-cefbb980-3e9a-11e9-8dc0-c61793e6e07d.png)

**Comment by CrazySummerday** [comment]
> I got the same error. The code uses all the OrderedDict in the wrong way, you can just turn the parameter from dict to list to remove the bug.
> ![snipaste_2019-03-04_16-30-09](https://user-images.githubusercontent.com/33656971/53720081-cefbb980-3e9a-11e9-8dc0-c61793e6e07d.png)
Your method solves this bug. Thanks!

**Comment by ehartz01** [comment]
Did you change every block to a list?

**Comment by CrazySummerday** [comment]
yes, you need to change every block.




------------------ 原始邮件 ------------------
发件人: "Ethan Hartzell"<notifications@github.com>;
发送时间: 2019年4月20日(星期六) 凌晨0:40
收件人: "Hzzone/pytorch-openpose"<pytorch-openpose@noreply.github.com>;
抄送: "Hans Hu"<413821561@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Hzzone/pytorch-openpose] runtime error for demo.jpg --RuntimeError: Given groups=1, weight of size [256, 512, 3, 3], expectedinput[1, 3, 46, 32] to have 512 channels, but got 3 channels instead (#2)




Did you change every block to a list?

**Comment by souljaboy764** [comment]
It would be nice to have this updated in the code
