### ISSUE TITLE
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by Jasonmes** [Hzzone/pytorch-openpose#26]
Traceback (most recent call last):
  File "/home/moziaijason/pycode/detection/pytorch-openpose-master/src/hand.py", line 89, in <module>
    canvas = util.draw_handpose(oriImg, peaks, True)
  File "/home/moziaijason/pycode/detection/pytorch-openpose-master/src/util.py", line 94, in draw_handpose
    if np.sum(np.all(peaks[e], axis=1)==0)==0:
  File "<__array_function__ internals>", line 6, in all
  File "/home/moziaijason/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2398, in all
    return _wrapreduction(a, np.logical_and, 'all', axis, None, out, keepdims=keepdims)
  File "/home/moziaijason/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

当我运行hand.py的时候，出现上面的错误，请问是怎么回事

**Comment by xiakj** [comment]
@Jasonmes 怎么解决的

**Comment by JiayuZou2020** [comment]
How to solve this problem? Did you find out the solution?
