### ISSUE TITLE
Can't open camera by index error when trying to use Kinect

### ISSUE THREAD

**Issue by femifapo** [Hzzone/pytorch-openpose#31]
Thank you guys for providing the PyTorch model.

I am trying to get it to work with Kinect using libfreenect2(Openkinect) on my desktop, but I get the error below.

Do you know of a way to resolve it? or
How do I change the settings to connect to Kinect?

(pytorch-openpose) User@computer:~/software/pytorch-openpose$ python demo_camera.py
Torch device: GeForce RTX 2080 Ti
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "demo_camera.py", line 22, in <module>
    candidate, subset = body_estimation(oriImg)
  File "/home/femifapo/software/pytorch-openpose/src/body.py", line 31, in __call__
    multiplier = [x * boxsize / oriImg.shape[0] for x in scale_search]
  File "/home/femifapo/software/pytorch-openpose/src/body.py", line 31, in <listcomp>
    multiplier = [x * boxsize / oriImg.shape[0] for x in scale_search]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Hzzone** [comment]
Your input image is None.

**Comment by femifapo** [comment]
Thanks for your response, I have been trying to understand why the input image is none. Is that because I have to find a way to detect the connect? 

The default script works on my Webcam (though a bit delayed).
