### ISSUE TITLE
ZeroDivisionError: float division by zero in body.py

### ISSUE THREAD

**Issue by Adeel-Intizar** [Hzzone/pytorch-openpose#47]
RuntimeWarning: invalid value encountered in true_divide
  vec = np.divide(vec, norm)
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    candidate, subset = body_estimation(oriImg)
  File "src\body.py", line 135, in __call__
    0.5 * oriImg.shape[0] / norm - 1, 0)
ZeroDivisionError: float division by zero

**Comment by Adeel-Intizar** [comment]
I managed to solve it, in case if anyone is looking for it, just add 1e-6 to the norm variable which is causing this error and the problem will be solved
