### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by zhangtsingtsi** [Hzzone/pytorch-openpose#76]
C:\Users\a505s\.conda\envs\pytorch-openpose\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "F:\pytorch-openpose\demo_video.py", line 77, in <module>
    ffprobe_result = ffprobe(args.file)
  File "F:\pytorch-openpose\demo_video.py", line 31, in ffprobe
    result = subprocess.run(command_array, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
  File "C:\Users\a505s\.conda\envs\pytorch-openpose\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\a505s\.conda\envs\pytorch-openpose\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\a505s\.conda\envs\pytorch-openpose\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

HELP!!

**Comment by zhangtsingtsi** [comment]
There is an error when I run "python demo_video.py 1.mp4"

**Comment by Hzzone** [comment]
Use absolute path.

**Comment by puterh** [comment]
Absolute path is not working.

**Comment by dd-rongfa** [comment]
我遇到了相同的问题了，你解决了么？

**Comment by skxmxm** [comment]
你没有下ffmpeg，再官网下载之后加到环境变量里就行了

**Comment by vielleicht-fe** [comment]
我在conda环境中使用pip install ffmpeg-python下载了ffmpeg，但是仍然有这个问题

**Comment by skxmxm** [comment]
> 我在conda环境中使用pip install ffmpeg-python下载了ffmpeg，但是仍然有这个问题

你可以尝试直接在ffmpeg官网下载，然后将目录加入环境变量，这样就可以命令行调用了

**Comment by Chortine** [comment]
sudo apt-get install ffmpeg
